name: my_app
description: A new Dart Glue project
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_glue: ^1.0.0
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
