name: dart_glue_cli
description: CLI tool for Dart Glue
version: 1.0.0

environment:
  sdk: ^3.5.0

executables:
  dart_glue: dart_glue

dependencies:
  args: ^2.4.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

